# run on main changes, to run tests
name: Main

on:
  push:
    branches:
      - main
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install ffuf
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go
          go install github.com/ffuf/ffuf@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: run subdomainers test 
        run: sh ./test/subdomainer.test.sh

      - name: run username_combiner test
        run: sh ./test/username_combiner.test.sh
