# run on main changes, to run tests
name: Main

on:
  push:
    branches:
      - main
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: run subdomainers test 
        run: |
          cd ./test 
          sh ./subdomainer.test.sh

      - name: run username_combiner test
        run: |
          cd ./test
          sh ./username_combiner.test.sh
