# run on main changes, to run tests
name: Test dicovery tools

on:
  push:
    branches:
      - main
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install ffuf
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go
          go install github.com/ffuf/ffuf@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: run subdomainers test 
        run: |
          cd test
          sh ./subdomainer.test.sh

      - name: run username_combiner test
        run: |
          cd test
          sh ./username_combiner.test.sh
